name: Release

on:
  pull_request_target:
    types: [closed]

jobs:
  release_job:
    uses: bedita/github-workflows/.github/workflows/release.yml@v2
    with:
      main_branch: 'main'
      dist_branches: '["main"]'
      package_json_version: 'true'
